%%  case: 109
%%~ Status generated by radio and injected into MAVLink stream.
function p = encode_RADIO_STATUS_v1_0(S)
	global pnum;
	if (isempty(pnum))
		pnum = 1;
	else
		pnum = uint8(mod(pnum+1,256));
	end
	head = uint8(254);
	len = uint8(9);
	sysid = uint8(S.h_sysid);
	id = uint8(S.h_id);
	messid = uint8(109);
	name = [ ...
		{'rssi'}	 ... %% Local signal strength
		{'remrssi'}	 ... %% Remote signal strength
		{'txbuf'}	 ... %% Remaining free buffer space in percent.
		{'noise'}	 ... %% Background noise level
		{'remnoise'} ... %% Remote background noise level
		{'rxerrors'} ... %% Receive errors
		{'fixed'}	 ... %% Count of error corrected packets
		];
	byte = [ 1 1 1 1 1 2 2 ];
	type = [ {'uint8'} {'uint8'} {'uint8'} {'uint8'} {'uint8'} {'uint16'} {'uint16'} ];

	p = [head len pnum sysid id messid];
	%% Encode rssi data field
	val = typecast(S.rssi,'uint8');
	val = reshape(val,1,length(val));
	p = [p typecast(val,'uint8')];

	%% Encode remrssi data field
	val = typecast(S.remrssi,'uint8');
	val = reshape(val,1,length(val));
	p = [p typecast(val,'uint8')];

	%% Encode txbuf data field
	val = typecast(S.txbuf,'uint8');
	val = reshape(val,1,length(val));
	p = [p typecast(val,'uint8')];

	%% Encode noise data field
	val = typecast(S.noise,'uint8');
	val = reshape(val,1,length(val));
	p = [p typecast(val,'uint8')];

	%% Encode remnoise data field
	val = typecast(S.remnoise,'uint8');
	val = reshape(val,1,length(val));
	p = [p typecast(val,'uint8')];

	%% Encode rxerrors data field
	val = typecast(S.rxerrors,'uint16');
	val = reshape(val,1,length(val));
	p = [p typecast(val,'uint8')];

	%% Encode fixed data field
	val = typecast(S.fixed,'uint16');
	val = reshape(val,1,length(val));
	p = [p typecast(val,'uint8')];

	p = [p typecast(checksum_v1_0(p(2:end)'),'uint8')];
return
