%%%%  case: 109
%%~ Status generated by radio and injected into MAVLink stream.
function p = encodeValues_RADIO_STATUS_v1_0(rssi,remrssi,txbuf,noise,remnoise,rxerrors,fixed)
	S.rssi = typecast(uint8(rssi),'uint8');		% Local signal strength
	S.remrssi = typecast(uint8(remrssi),'uint8');		% Remote signal strength
	S.txbuf = typecast(uint8(txbuf),'uint8');		% Remaining free buffer space in percent.
	S.noise = typecast(uint8(noise),'uint8');		% Background noise level
	S.remnoise = typecast(uint8(remnoise),'uint8');		% Remote background noise level
	S.rxerrors = typecast(uint16(rxerrors),'uint16');		% Receive errors
	S.fixed = typecast(uint16(fixed),'uint16');		% Count of error corrected packets
	p = encode_RADIO_STATUS_v1_0(S);
return
