%%  case: 109
%%~ Status generated by radio and injected into MAVLink stream.
function S = parse_RADIO_STATUS_v1_0(p)
	name = [ ...
		{'rssi'}	 ... %% Local signal strength
		{'remrssi'}	 ... %% Remote signal strength
		{'txbuf'}	 ... %% Remaining free buffer space in percent.
		{'noise'}	 ... %% Background noise level
		{'remnoise'} ... %% Remote background noise level
		{'rxerrors'} ... %% Receive errors
		{'fixed'}	 ... %% Count of error corrected packets
		];
	byte = [ 1 1 1 1 1 2 2 ];
	type = [ {'uint8'} {'uint8'} {'uint8'} {'uint8'} {'uint8'} {'uint16'} {'uint16'} ];

	len = p(2);
	if (sum(byte) == len)
		S = buildStruct(byte,name,type,p);
	else
		S = [];
		disp('bytes in packet did not match structure size')
	end
return

