function tdata = getClassifyTrainingData()
%%
pALL = []; % List of ALL individual cases
pIDX = []; % Index list for each case group
disp(sprintf('Evaluating Parameters in working directory\n%s',pwd))
%%%   
    load('Parameter.mat');
    pList = [...
             {'MT_NoLoadSine_01'}; ...
             {'MT_NoLoadSine_02'}; ...
             {'MT_NoLoadSine_03'}; ...
             {'MT_NoLoadSine_04'}; ...
             {'MT_NoLoadSine_05'}; ...
             {'MT_NoLoadSine_06'}; ...
             {'MT_NoLoadSine_07'}; ...
             {'MT_NoLoadSine_08'}; ...
             {'MT_NoLoadSine_09'}; ...
             {'MT_NoLoadSine_10'}; ...
             {'MT_NoLoadSine_11'}; ...
             {'MT_NoLoadSine_12'}; ...
             {'MT_NoLoadSine_13'}; ...
             {'MT_NoLoadSine_14'}; ...
             {'MT_NoLoadSine_15'}; ...
             {'MT_NoLoadSine_16'}; ...
             {'MT_NoLoadSine_17'} ...
            ];
    pIDX{1} = (length(pALL)+1:length(pALL)+length(pList))';
    pALL = [pALL; pList];
    NLSN = extractParameters(p,pList);

    pList = [...
             {'MT_NoLoadDive_01'}; ...
             {'MT_NoLoadDive_02'}; ...
             {'MT_NoLoadDive_03'}; ...
             {'MT_NoLoadDive_04'}; ...
             {'MT_NoLoadDive_05'}; ...
             {'MT_NoLoadDive_06'}; ...
             {'MT_NoLoadDive_07'}; ...
             {'MT_NoLoadDive_08'}; ...
             {'MT_NoLoadDive_09'}; ...
             {'MT_NoLoadDive_10'} ...
             ];
    pIDX{2} = (length(pALL)+1:length(pALL)+length(pList))';
    pALL = [pALL; pList];
    NLDV = extractParameters(p,pList);
   
    pList = [...
             {'MT_NoLoadBLWN_01'}; ...
             {'MT_NoLoadBLWN_02'}; ...
             {'MT_NoLoadBLWN_03'} ...
             ];
    pIDX{3} = (length(pALL)+1:length(pALL)+length(pList))';
    pALL = [pALL; pList];
    NLWN = extractParameters(p,pList);
    
    pList = [...
             {'MT_NoLoad_FastSine_01'}; ...
             {'MT_NoLoad_FastSine_02'}; ...
             {'MT_NoLoad_FastSine_03'} ...
             ];
    pIDX{4} = (length(pALL)+1:length(pALL)+length(pList))';
    pALL = [pALL; pList];
    NLFS = extractParameters(p,pList);
   
    pList = [...
             {'MT_NoLoad_SlowSine_01'}; ...
             {'MT_NoLoad_SlowSine_02'}; ...
             {'MT_NoLoad_SlowSine_03'} ...
             ];
    pIDX{5} = (length(pALL)+1:length(pALL)+length(pList))';
    pALL = [pALL; pList];
    NLSS = extractParameters(p,pList);
    
%%%---------------------------------
    pList = [...
             {'MT_05LoadSine_01'}; ...
             {'MT_05LoadSine_02'}; ...
             {'MT_10LoadSine_01'}; ...
             {'MT_10LoadSine_02'}; ...
             {'MT_15LoadSine_01'}; ...
             {'MT_15LoadSine_02'}; ...
             {'MT_25LoadSine_01'}; ...
             {'MT_25LoadSine_02'}; ...
             {'MT_50LoadSine_01'}; ...
             {'MT_50LoadSine_02'}; ...
             {'MT_LoadSine_01'}; ...
             {'MT_LoadSine_02'}; ...
             {'MT_LoadSine_03'}; ...
             {'MT_LoadSine_04'}; ...
             {'MT_LoadSine_05'}; ...
             {'MT_LoadSine_06'}; ...
             {'MT_LoadSine_07'}; ...
             {'MT_LoadSine_08'}; ...
             {'MT_LoadSine_09'}; ...
             {'MT_LoadSine_10'} ...
             ];
    pIDX{6} = (length(pALL)+1:length(pALL)+length(pList))';
    pALL = [pALL; pList];
    LSN = extractParameters(p,pList);

    pList = [...
             {'MT_LoadDive_01'}; ...
             {'MT_LoadDive_02'}; ...
             {'MT_LoadDive_03'}; ...
             {'MT_LoadDive_04'}; ...
             {'MT_LoadDive_05'}; ...
             {'MT_LoadDive_06'}; ...
             {'MT_LoadDive_07'}; ...
             {'MT_LoadDive_08'}; ...
             {'MT_LoadDive_09'}; ...
             {'MT_LoadDive_10'} ...
             ];
    pIDX{7} = (length(pALL)+1:length(pALL)+length(pList))';
    pALL = [pALL; pList];
    LDV = extractParameters(p,pList);
  
    pList = [...
             {'MT_05LoadBLWN_01'}; ...
             {'MT_05LoadBLWN_02'}; ...
             {'MT_10LoadBLWN_01'}; ...
             {'MT_10LoadBLWN_02'}; ...
             {'MT_15LoadBLWN_01'}; ...
             {'MT_15LoadBLWN_02'} ...
             ];
    pIDX{8} = (length(pALL)+1:length(pALL)+length(pList))';
    pALL = [pALL; pList];
    LWN = extractParameters(p,pList);

    pList = [...
             {'MT_Load530g_FastSine_01'}; ...
             {'MT_Load530g_FastSine_02'}; ...
             {'MT_Load530g_FastSine_03'} ...
             ];
    pIDX{9} = (length(pALL)+1:length(pALL)+length(pList))';
    pALL = [pALL; pList];
    LFS = extractParameters(p,pList);
    
    pList = [...
             {'MT_Load530g_SlowSine_01'}; ...
             {'MT_Load530g_SlowSine_02'}; ...
             {'MT_Load530g_SlowSine_03'} ...
             ];
    pIDX{10} = (length(pALL)+1:length(pALL)+length(pList))';
    pALL = [pALL; pList];
    LSS = extractParameters(p,pList);
    
%     tdata.param = [{NLSN}; ...
%                    {NLDV}; ...
%                    {NLWN}; ...
%                    {NLFS}; ...
%                    {NLSS}; ...
%                    {LSN} ; ...
%                    {LDV} ; ...
%                    {LWN} ; ...
%                    {LFS} ; ...
%                    {LSS}];
    tdata.NLSN = NLSN;
    tdata.NLDV = NLDV;
    tdata.NLWN = NLWN;
    tdata.NLFS = NLFS;
    tdata.NLSS = NLSS;
    tdata.LSN  = LSN;
    tdata.LDV  = LDV;
    tdata.LWN  = LWN;
    tdata.LFS  = LFS;
    tdata.LSS  = LSS;
    tdata.idx  = pIDX(:);
    tdata.list = pALL;
return
