%% Merge Structures (incomplete)
    clear
    % Load Struct1
    load('.mat');
    Struct1 = xxx;
    clear xxx
    
    % Load Struct2
    load('.mat');
    Struct2 = xxx;
    clear xxx
    
    Fields1 = fieldnames(Struct1);
    Fields2 = fieldnames(Struct2);
    
    N1 = length(Fields1);
    N2 = length(Fields2);
    
    for i=1:N1
        xxx.(Fields1{i}) = Struct1.(Fields1{i});
    end
    for i=1:N2
        xxx.(Fields2{i}) = Struct2.(Fields2{i});
    end
    
    save('.mat','xxx');

%% Damage flag keys
% 0 = no damage
% 1 = load at tip (maybe classify using moments = load * distance)
% 2 = load else where

%% Motion flag keys
% 1 = BLWN
% 2 = cyclic (freq?)
% 3 = single event (Dives)

%% Use 'E:\edafi\My Documents\LabVIEW Data\MT_Multiple Cases'
%% BLWN
p_MT_NoLoadBLWN_02 = getParameterList('MT_NoLoadBLWN_02',0,0);

p_MT_NoLoadBLWN_03 = getParameterList('MT_NoLoadBLWN_03',0,0);

p_MT_NoLoadBLWN_02.bip.sd = ...
    getTwoTailedParameters(p_MT_NoLoadBLWN_02.dCase, p_MT_NoLoadBLWN_03.bip.sd, p_MT_NoLoadBLWN_02.bip.sd, 0, 1);
p_MT_NoLoadBLWN_02.uni.sd = ...
    getTwoTailedParameters(p_MT_NoLoadBLWN_02.dCase, p_MT_NoLoadBLWN_03.uni.sd, p_MT_NoLoadBLWN_02.uni.sd, 0, 1);

p_MT_NoLoadBLWN_03.bip.sd = ...
    getTwoTailedParameters(p_MT_NoLoadBLWN_03.dCase, p_MT_NoLoadBLWN_02.bip.sd, p_MT_NoLoadBLWN_03.bip.sd, 0, 1);
p_MT_NoLoadBLWN_03.uni.sd = ...
    getTwoTailedParameters(p_MT_NoLoadBLWN_03.dCase, p_MT_NoLoadBLWN_02.uni.sd, p_MT_NoLoadBLWN_03.uni.sd, 0, 1);


%% Process ALL Cases in Folder
%% 
    clear
    % Preload baseline spectrums for OBAccOnly
    load('MT_NoLoadBLWN_02_baseSD_OBaccOnly.mat');
    baseOBaccOnly = base;
    
    % Preload baseline spectrums for OBCGAccDiff
    load('MT_NoLoadBLWN_02_baseSD_OBCGAccDiff.mat');
    baseOBCGAccDiff = base;
    clear base

    dlist = dir('*');
    N = length(dlist);
    for i=1:N
        if dlist(i).isdir
            dName = dlist(i).name;
            dFile = dir(sprintf('%s\\PC104.mat',dName));
            if ~isempty(dFile)
                disp(sprintf('Processing %s ...',dName))
                p.(dName) = getParameterList(dName,-1,-1, baseOBaccOnly, baseOBCGAccDiff  );
            end
        end
    end
    disp('Saving data to mat file ...')
    save('Parameter.mat','p');
    disp(sprintf('Completed all directories in %s ...',pwd()))
    
%% Group Parameters
%%
    pList = [...
             {'MT_NoLoad_FastSine_01'} ...
             {'MT_NoLoad_FastSine_02'} ...
             {'MT_NoLoad_FastSine_03'} ...
             ];
    NLFS = extractParameters(p,pList);
   
    pList = [...
             {'MT_NoLoad_SlowSine_01'} ...
             {'MT_NoLoad_SlowSine_02'} ...
             {'MT_NoLoad_SlowSine_03'} ...
             ];
    NLSS = extractParameters(p,pList);
    
    pList = [...
             {'MT_Load530g_FastSine_01'} ...
             {'MT_Load530g_FastSine_02'} ...
             {'MT_Load530g_FastSine_03'} ...
             ];
    LFS = extractParameters(p,pList);
    
    pList = [...
             {'MT_Load530g_SlowSine_01'} ...
             {'MT_Load530g_SlowSine_02'} ...
             {'MT_Load530g_SlowSine_03'} ...
             ];
    LSS = extractParameters(p,pList);
%%    
    MS = 10;
    slvFigure('Test Plot'); 
    subplot(2,1,1); hold off
    plot(1  ,NLFS.bip.slope,'bo','MarkerSize',MS); hold on
    plot(2  ,NLSS.bip.slope,'bo','MarkerSize',MS)
    plot(3  ,LFS.bip.slope ,'ro','MarkerSize',MS)
    plot(4  ,LSS.bip.slope ,'ro','MarkerSize',MS)
 
    plot(1  ,NLFS.uni.slope,'bd','MarkerSize',MS)
    plot(2  ,NLSS.uni.slope,'bd','MarkerSize',MS)
    plot(3  ,LFS.uni.slope ,'rd','MarkerSize',MS)
    plot(4  ,LSS.uni.slope ,'rd','MarkerSize',MS)
    xlim([0 5])
    grid on
    
    subplot(2,1,2); hold off
    plot(1  ,NLFS.bip.slope,'bo','MarkerSize',MS); hold on
    plot(3  ,NLSS.bip.slope,'bo','MarkerSize',MS)
    plot(1  ,LFS.bip.slope ,'ro','MarkerSize',MS)
    plot(3  ,LSS.bip.slope ,'ro','MarkerSize',MS)
 
    plot(2  ,NLFS.uni.slope,'bd','MarkerSize',MS)
    plot(4  ,NLSS.uni.slope,'bd','MarkerSize',MS)
    plot(2  ,LFS.uni.slope ,'rd','MarkerSize',MS)
    plot(4  ,LSS.uni.slope ,'rd','MarkerSize',MS)
    xlim([0 5])
    grid on
    
%%   
    pList = [...
             {'MT_LoadDive_01'} ...
             {'MT_LoadDive_02'} ...
             {'MT_LoadDive_03'} ...
             {'MT_LoadDive_04'} ...
             {'MT_LoadDive_05'} ...
             {'MT_LoadDive_06'} ...
             {'MT_LoadDive_07'} ...
             {'MT_LoadDive_08'} ...
             {'MT_LoadDive_09'} ...
             {'MT_LoadDive_10'} ...
             ];
    LDV = extractParameters(p,pList);
  
    pList = [...
             {'MT_05LoadSine_01'} ...
             {'MT_05LoadSine_02'} ...
             {'MT_10LoadSine_01'} ...
             {'MT_10LoadSine_02'} ...
             {'MT_15LoadSine_01'} ...
             {'MT_15LoadSine_02'} ...
             {'MT_25LoadSine_01'} ...
             {'MT_25LoadSine_02'} ...
             {'MT_50LoadSine_01'} ...
             {'MT_50LoadSine_02'} ...
             {'MT_LoadSine_01'} ...
             {'MT_LoadSine_02'} ...
             {'MT_LoadSine_03'} ...
             {'MT_LoadSine_04'} ...
             {'MT_LoadSine_05'} ...
             {'MT_LoadSine_06'} ...
             {'MT_LoadSine_07'} ...
             {'MT_LoadSine_08'} ...
             {'MT_LoadSine_09'} ...
             {'MT_LoadSine_10'} ...
             ];
    LSN = extractParameters(p,pList);

    pList = [...
             {'MT_NoLoadDive_01'} ...
             {'MT_NoLoadDive_02'} ...
             {'MT_NoLoadDive_03'} ...
             {'MT_NoLoadDive_04'} ...
             {'MT_NoLoadDive_05'} ...
             {'MT_NoLoadDive_06'} ...
             {'MT_NoLoadDive_07'} ...
             {'MT_NoLoadDive_08'} ...
             {'MT_NoLoadDive_09'} ...
             {'MT_NoLoadDive_10'} ...
             ];
    NLDV = extractParameters(p,pList);
   
    pList = [...
             {'MT_NoLoadSine_01'} ...
             {'MT_NoLoadSine_02'} ...
             {'MT_NoLoadSine_03'} ...
             {'MT_NoLoadSine_04'} ...
             {'MT_NoLoadSine_05'} ...
             {'MT_NoLoadSine_06'} ...
             {'MT_NoLoadSine_07'} ...
             {'MT_NoLoadSine_08'} ...
             {'MT_NoLoadSine_09'} ...
             {'MT_NoLoadSine_10'} ...
             {'MT_NoLoadSine_11'} ...
             {'MT_NoLoadSine_12'} ...
             {'MT_NoLoadSine_13'} ...
             {'MT_NoLoadSine_14'} ...
             {'MT_NoLoadSine_15'} ...
             {'MT_NoLoadSine_16'} ...
             {'MT_NoLoadSine_17'} ...
            ];
    NLSN = extractParameters(p,pList);

    pList = [...
             {'MT_05LoadBLWN_01'} ...
             {'MT_05LoadBLWN_02'} ...
             {'MT_10LoadBLWN_01'} ...
             {'MT_10LoadBLWN_02'} ...
             {'MT_15LoadBLWN_01'} ...
             {'MT_15LoadBLWN_02'} ...
             ];
    LWN = extractParameters(p,pList);

    pList = [...
             {'MT_NoLoadBLWN_01'} ...
             {'MT_NoLoadBLWN_02'} ...
             {'MT_NoLoadBLWN_03'} ...
             ];
    NLWN = extractParameters(p,pList);
    
     pList = [...
             {'MT_NoLoad_FastSine_01'} ...
             {'MT_NoLoad_FastSine_02'} ...
             {'MT_NoLoad_FastSine_03'} ...
             ];
    NLFS = extractParameters(p,pList);
   
    pList = [...
             {'MT_NoLoad_SlowSine_01'} ...
             {'MT_NoLoad_SlowSine_02'} ...
             {'MT_NoLoad_SlowSine_03'} ...
             ];
    NLSS = extractParameters(p,pList);
    
    pList = [...
             {'MT_Load530g_FastSine_01'} ...
             {'MT_Load530g_FastSine_02'} ...
             {'MT_Load530g_FastSine_03'} ...
             ];
    LFS = extractParameters(p,pList);
    
    pList = [...
             {'MT_Load530g_SlowSine_01'} ...
             {'MT_Load530g_SlowSine_02'} ...
             {'MT_Load530g_SlowSine_03'} ...
             ];
    LSS = extractParameters(p,pList);
   
    
%% Use 'E:\edafi\My Documents\LabVIEW Data\MT_KenWave_VaryLoadPos'
%% KenWave
p_00g_000mm = getParameterList('MT_00g_000mm',0,0);
p_50g_170mm = getParameterList('MT_50g_170mm',1,0);
p_50g_338mm = getParameterList('MT_50g_338mm',1,0);
p_50g_520mm = getParameterList('MT_50g_520mm',1,0);


%%

p_MT_05LoadBLWN_01 = getParameterList('MT_05LoadBLWN_01',1,0, baseOBaccOnly, baseOBCGAccDiff);
%%
p_MT_05LoadBLWN_02 = getParameterList('MT_05LoadBLWN_02',1,0);
p_MT_10LoadBLWN_01 = getParameterList('MT_10LoadBLWN_01',1,0);
p_MT_10LoadBLWN_02 = getParameterList('MT_10LoadBLWN_02',1,0);
p_MT_15LoadBLWN_01 = getParameterList('MT_15LoadBLWN_01',1,0);
p_MT_15LoadBLWN_02 = getParameterList('MT_15LoadBLWN_02',1,0);

%% Use 'E:\edafi\My Documents\LabVIEW Data\MT_Experiment Mar 02 2010'
%% SLOW
p_MT_NoLoad_SlowSine_01 = getParameterList('MT_NoLoad_SlowSine_01',0,0);
%%
p_MT_NoLoad_SlowSine_02 = getParameterList('MT_NoLoad_SlowSine_02',0,0);
p_MT_NoLoad_SlowSine_03 = getParameterList('MT_NoLoad_SlowSine_03',0,0);

%% FAST
p_MT_NoLoad_FastSine_01 = getParameterList('MT_NoLoad_FastSine_01',0,0);
p_MT_NoLoad_FastSine_02 = getParameterList('MT_NoLoad_FastSine_02',0,0);
p_MT_NoLoad_FastSine_03 = getParameterList('MT_NoLoad_FastSine_03',0,0);

%% SLOW
p_MT_Load530g_SlowSine_01 = getParameterList('MT_Load530g_SlowSine_01',1,0);
p_MT_Load530g_SlowSine_02 = getParameterList('MT_Load530g_SlowSine_02',1,0);
p_MT_Load530g_SlowSine_03 = getParameterList('MT_Load530g_SlowSine_03',1,0);

%% FAST
p_MT_Load530g_FastSine_01 = getParameterList('MT_Load530g_FastSine_01',1,0);
p_MT_Load530g_FastSine_02 = getParameterList('MT_Load530g_FastSine_02',1,0);
p_MT_Load530g_FastSine_03 = getParameterList('MT_Load530g_FastSine_03',1,0);
