%%
function plotIMU(dfile)
    load(dfile);

    h = [];
    slvFigure(dfile);
    h = [h subplot(3,1,1)];
    hold off
    plot(MavLink_ts.RAW_IMU.xacc.time, ...
         MavLink_ts.RAW_IMU.xacc.data, ':r.');
    hold on
    plot(MavLink_ts.RAW_IMU.yacc.time, ...
         MavLink_ts.RAW_IMU.yacc.data, 'g.');
    plot(MavLink_ts.RAW_IMU.zacc.time, ...
         MavLink_ts.RAW_IMU.zacc.data, ':b.');
    plot(MavLink_ts.RAW_IMU.xacc.time, ...
         sqrt(MavLink_ts.RAW_IMU.xacc.data.^2 + ...
              MavLink_ts.RAW_IMU.yacc.data.^2 + ...
              MavLink_ts.RAW_IMU.zacc.data.^2), ':k.');
    %ylim([-4 4]);
    grid on
    legend([{'acc.x'} {'acc.y'} {'acc.z'} {'|acc|'}],'Location','West')

    h = [h subplot(3,1,2)];
    hold off
    plot(MavLink_ts.RAW_IMU.xgyro.time, ...
         MavLink_ts.RAW_IMU.xgyro.data, ':r.');
    hold on
    plot(MavLink_ts.RAW_IMU.ygyro.time, ...
         MavLink_ts.RAW_IMU.ygyro.data, 'g.');
    plot(MavLink_ts.RAW_IMU.zgyro.time, ...
         MavLink_ts.RAW_IMU.zgyro.data, ':b.');
    plot(MavLink_ts.RAW_IMU.xgyro.time, ...
         sqrt(MavLink_ts.RAW_IMU.xgyro.data.^2 + ...
              MavLink_ts.RAW_IMU.ygyro.data.^2 + ...
              MavLink_ts.RAW_IMU.zgyro.data.^2), ':k.');
    %ylim([-40 60]);
    grid on
    legend([{'gyro.x'} {'gyro.y'} {'gyro.z'} {'|gyro|'}],'Location','West')

    h = [h subplot(3,1,3)];
    hold off
    plot(MavLink_ts.RAW_IMU.xmag.time, ...
         MavLink_ts.RAW_IMU.xmag.data, ':r.');
    hold on
    plot(MavLink_ts.RAW_IMU.ymag.time, ...
         MavLink_ts.RAW_IMU.ymag.data, 'g.');
    plot(MavLink_ts.RAW_IMU.zmag.time, ...
         MavLink_ts.RAW_IMU.zmag.data, ':b.');
    plot(MavLink_ts.RAW_IMU.xmag.time, ...
         sqrt(MavLink_ts.RAW_IMU.xmag.data.^2 + ...
              MavLink_ts.RAW_IMU.ymag.data.^2 + ...
              MavLink_ts.RAW_IMU.zmag.data.^2), ':k.');
    %ylim([-600 800]);
    grid on
    legend([{'mag.x'} {'mag.y'} {'mag.z'} {'|mag|'}],'Location','West')
    linkaxes(h,'x');
return
