%%
F2MAPPING = [10:32 ...];
F3MAPPING = 1:73;

%%
pc104.Variables = {'ADC01' ...
                   'ADC02' ...
                   'ADC03' ...
                   'ADC04' ...
                   'ADC05' ...
                   'ADC06' ...
                   'ADC07' ...
                   'ADC08' ...
                   'ADC09' ...
                   'ADC10' ...
                   'ADC11' ...
                   'ADC12' ...
                   'ADC13' ...
                   'ADC14' ...
                   'ADC15' ...
                   'ADC16' ...
                   'ADC17' ...
                   'ADC18' ...
                   'ADC19' ...
                   'ADC20' ...
                   'ADC21' ...
                   'ADC22' ...
                   'ADC23' ...
                   'ADC24' ...
                   'ADC25' ...
                   'ADC26' ...
                   'ADC27' ...
                   'ADC28' ...
                   'ADC29' ...
                   'ADC30' ...
                   'ADC31' ...
                   'ADC32' ...
                   'E1' ...
                   'DIN2' ...
                   'DIN3' ...
                   'DIN4' ...
                   'DIN5' ...
                   'DIN6' ...
                   'DIN7' ...
                   'DIN8' ...
                   'LWOBSTRN' ...
                   'LWCTRSTRN' ...
                   'LWIBSTRN' ...
                   'CTRLSTRN' ...
                   'CTRCSTRN' ...
                   'CTRRSTRN' ...
                   'RWIBSTRN' ...
                   'RWCTRSTRN' ...
                   'RWOBSTRN' ...
                   'MTRMOUNTTEMP' ...
                   'MTRAIRTEMP' ...
                   'LFTOPBATTEMP' ...
                   'LFBOTBATTEMP' ...
                   'RTTOPBATTEMP' ...
                   'RTBOTBATTEMP' ...
                   'FRNTMTRCUR' ...
                   'REARMTRCUR' ...
                   'LWOBACCLX' ...
                   'LWOBACCLY' ...
                   'LWOBACCLZ' ...
                   'LWIBACCLX' ...
                   'LWIBACCLY' ...
                   'LWIBACCLZ' ...
                   'RWIBACCLX' ...
                   'RWIBACCLY' ...
                   'RWIBACCLZ' ...
                   'RWOBACCLX' ...
                   'RWOBACCLY' ...
                   'RWOBACCLZ' ...
                   'CTRACCLX' ...
                   'CTRACCLY' ...
                   'CTRACCLZ' ...
                   'TIME'}';

pc104.Description = {'' ...
                     'Left Wing Outboard Strain' ...
                     'Left Wing Center Strain' ...
                     'Left Wing Inboard Strain' ...
                     'Wing Tube Left Strain' ...
                     'Wing Tube Center Strain' ...
                     'Wing Tube Right Strain' ...
                     'Right Wing Inboard Strain' ...
                     'Right Wing Center Strain' ...
                     'Right Wing Outboard Strain' ...
                     'Motor Mount Temperature' ...
                     'Motor Exit Air Temperature' ...
                     'Left Top Battery Temperature' ...
                     'Left Bottom Battery Temperature' ...
                     'Right Top Battery Temperature' ...
                     'Right Bottom Battery Temperature' ...
                     'Front Motor Current' ...
                     'Rear Motor Current' ...
                     'Left Wing Outboard Accelerometer X axis' ...
                     'Left Wing Outboard Accelerometer Y axis' ...
                     'Left Wing Outboard Accelerometer Z axis' ...
                     'Left Wing Inboard Accelerometer X axis' ...
                     'Left Wing Inboard Accelerometer Y axis' ...
                     'Left Wing Inboard Accelerometer Z axis' ...
                     'Right Wing Inboard Accelerometer X axis' ...
                     'Right Wing Inboard Accelerometer Y axis' ...
                     'Right Wing Inboard Accelerometer Z axis' ...
                     'Right Wing Outboard Accelerometer X axis' ...
                     'Right Wing Outboard Accelerometer Y axis' ...
                     'Right Wing Outboard Accelerometer Z axis' ...
                     'Center Wing Accelerometer X axis' ...
                     'Center Wing Accelerometer Y axis' ...
                     'Center Wing Accelerometer Z axis' ...
                     'Event Marker' ...
                     'spare2' ...
                     'spare3' ...
                     'spare4' ...
                     'spare5' ...
                     'spare6' ...
                     'spare7' ...
                     'spare8' ...
                     'Left Wing Outboard Strain' ...
                     'Left Wing Center Strain' ...
                     'Left Wing Inboard Strain' ...
                     'Wing Tube Left Strain' ...
                     'Wing Tube Center Strain' ...
                     'Wing Tube Right Strain' ...
                     'Right Wing Inboard Strain' ...
                     'Right Wing Center Strain' ...
                     'Right Wing Outboard Strain' ...
                     'Motor Mount Temperature' ...
                     'Motor Exit Air Temperature' ...
                     'Left Top Battery Temperature' ...
                     'Left Bottom Battery Temperature' ...
                     'Right Top Battery Temperature' ...
                     'Right Bottom Battery Temperature' ...
                     'Front Motor Current' ...
                     'Rear Motor Current' ...
                     'Left Wing Outboard Accelerometer X axis' ...
                     'Left Wing Outboard Accelerometer Y axis' ...
                     'Left Wing Outboard Accelerometer Z axis' ...
                     'Left Wing Inboard Accelerometer X axis' ...
                     'Left Wing Inboard Accelerometer Y axis' ...
                     'Left Wing Inboard Accelerometer Z axis' ...
                     'Right Wing Inboard Accelerometer X axis' ...
                     'Right Wing Inboard Accelerometer Y axis' ...
                     'Right Wing Inboard Accelerometer Z axis' ...
                     'Right Wing Outboard Accelerometer X axis' ...
                     'Right Wing Outboard Accelerometer Y axis' ...
                     'Right Wing Outboard Accelerometer Z axis' ...
                     'Center Wing Accelerometer X axis' ...
                     'Center Wing Accelerometer X axis' ...
                     'Center Wing Accelerometer X axis' ...
                     'Time'}';

                 