%%
class = [];
dlist = [];

class = [class; {'No Damage'}];
dlist = [dlist; {[ ...
            {'MT_NoLoadSine'}; ...
            {'MT_NoLoadSine_01'}; ...
            {'MT_NoLoadSine_02'}; ...
            {'MT_NoLoadSine_03'}; ...
            {'MT_NoLoadSine_04'}; ...
            {'MT_NoLoadSine_05'}; ...
            {'MT_NoLoadSine_06'}; ...
            {'MT_NoLoadSine_07'}; ...
            {'MT_NoLoad_BLWN_01'}; ...
            {'MT_NoLoad_BLWN_02'}; ...
            {'MT_NoLoad_BLWN_03'}; ...
            {'MT_NoLoad_BLWN_04'}; ...
            {'MT_NoLoad_BLWN_05'}; ...
            {'MT_NoLoad_BLWN_06'}; ...
            {'MT_NoLoad_Dive'}; ...
            {'MT_NoLoad_Dive_01'}; ...
            {'MT_NoLoad_Dive_02'}; ...
            {'MT_NoLoad_Dive_03'}; ...
            {'MT_NoLoad_Dive_04'}; ...
            {'MT_NoLoad_Dive_05'}; ...
            {'MT_NoLoad_Dive_06'}; ...
            {'MT_NoLoad_FastSine'}; ...
            {'MT_NoLoad_FastSine_01'}; ...
            {'MT_NoLoad_FastSine_02'}; ...
            {'MT_NoLoad_FastSine_03'}; ...
            {'MT_NoLoad_FastSine_04'}; ...
            {'MT_NoLoad_FastSine_05'}; ...
            {'MT_NoLoad_FastSine_06'}; ...
            {'MT_NoLoad_SlowSine_01'}; ...
            {'MT_NoLoad_SlowSine_02'}; ...
            {'MT_NoLoad_SlowSine_03'}; ...
            {'MT_NoLoad_SlowSine_04'}; ...
            {'MT_NoLoad_SlowSine_05'}; ...
            {'MT_NoLoad_SlowSine_06'}; ...
           ]}];
       
class = [class; {'Tip Load'}];
dlist = [dlist; {[ ...
            {'MT_Load250g_Tip_BLWN_01'}; ...
            {'MT_Load250g_Tip_BLWN_02'}; ...
            {'MT_Load250g_Tip_BLWN_03'}; ...
            {'MT_Load250g_Tip_BLWN_04'}; ...
            {'MT_Load250g_Tip_Dive'}; ...
            {'MT_Load250g_Tip_Dive_01'}; ...
            {'MT_Load250g_Tip_Dive_02'}; ...
            {'MT_Load250g_Tip_Dive_03'}; ...
            {'MT_Load250g_Tip_Dive_04'}; ...
            {'MT_Load250g_Tip_FastSine'}; ...
            {'MT_Load250g_Tip_FastSine_01'}; ...
            {'MT_Load250g_Tip_FastSine_02'}; ...
            {'MT_Load250g_Tip_FastSine_03'}; ...
            {'MT_Load250g_Tip_FastSine_04'}; ...
            {'MT_Load250g_Tip_Sine'}; ...
            {'MT_Load250g_Tip_Sine_01'}; ...
            {'MT_Load250g_Tip_Sine_02'}; ...
            {'MT_Load250g_Tip_Sine_03'}; ...
            {'MT_Load250g_Tip_Sine_04'}; ...
            {'MT_Load250g_Tip_SlowSine_01'}; ...
            {'MT_Load250g_Tip_SlowSine_02'}; ...
            {'MT_Load250g_Tip_SlowSine_03'}; ...
            {'MT_Load250g_Tip_SlowSine_04'}; ...
            {'MT_Load530g_Tip_BLWN_01'}; ...
            {'MT_Load530g_Tip_BLWN_02'}; ...
            {'MT_Load530g_Tip_BLWN_03'}; ...
            {'MT_Load530g_Tip_BLWN_04'}; ...
            {'MT_Load530g_Tip_Dive'}; ...
            {'MT_Load530g_Tip_Dive_01'}; ...
            {'MT_Load530g_Tip_Dive_02'}; ...
            {'MT_Load530g_Tip_Dive_03'}; ...
            {'MT_Load530g_Tip_Dive_04'}; ...
            {'MT_Load530g_Tip_FastSine'}; ...
            {'MT_Load530g_Tip_FastSine_01'}; ...
            {'MT_Load530g_Tip_FastSine_02'}; ...
            {'MT_Load530g_Tip_FastSine_03'}; ...
            {'MT_Load530g_Tip_FastSine_04'}; ...
            {'MT_Load530g_Tip_Sine'}; ...
            {'MT_Load530g_Tip_Sine_01'}; ...
            {'MT_Load530g_Tip_Sine_02'}; ...
            {'MT_Load530g_Tip_Sine_03'}; ...
            {'MT_Load530g_Tip_Sine_04'}; ...
            {'MT_Load530g_Tip_SlowSine'}; ...
            {'MT_Load530g_Tip_SlowSine_01'}; ...
            {'MT_Load530g_Tip_SlowSine_02'}; ...
            {'MT_Load530g_Tip_SlowSine_03'}; ...
            {'MT_Load530g_Tip_SlowSine_04'}; ...
           ]}];
       
class = [class; {'OBCTR Load'}];
dlist = [dlist; {[ ...
            {'MT_Load250g_OBCTR_BLWN_01'}; ...
            {'MT_Load250g_OBCTR_BLWN_02'}; ...      
            {'MT_Load250g_OBCTR_BLWN_03'}; ...
            {'MT_Load250g_OBCTR_BLWN_04'}; ...
            {'MT_Load250g_OBCTR_Dive'}; ...
            {'MT_Load250g_OBCTR_Dive_01'}; ...
            {'MT_Load250g_OBCTR_Dive_02'}; ...
            {'MT_Load250g_OBCTR_Dive_03'}; ...
            {'MT_Load250g_OBCTR_Dive_04'}; ...
            {'MT_Load250g_OBCTR_FastSine'}; ...
            {'MT_Load250g_OBCTR_FastSine_01'}; ...
            {'MT_Load250g_OBCTR_FastSine_02'}; ...
            {'MT_Load250g_OBCTR_FastSine_03'}; ...
            {'MT_Load250g_OBCTR_FastSine_04'}; ...
            {'MT_Load250g_OBCTR_Sine'}; ...
            {'MT_Load250g_OBCTR_Sine_01'}; ...
            {'MT_Load250g_OBCTR_Sine_02'}; ...
            {'MT_Load250g_OBCTR_Sine_03'}; ...
            {'MT_Load250g_OBCTR_Sine_04'}; ...
            {'MT_Load250g_OBCTR_SlowSine'}; ...
            {'MT_Load250g_OBCTR_SlowSine_01'}; ...
            {'MT_Load250g_OBCTR_SlowSine_02'}; ...
            {'MT_Load250g_OBCTR_SlowSine_03'}; ...
            {'MT_Load250g_OBCTR_SlowSine_04'}; ...
           ]}];
       
N = length(dlist);
for i=1:N
    dN(i) = length(dlist{i});
end

save('dList.mat','dlist','class','dN');
